/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all categories
         * @description Retrieve a list of all Dutch culture categories
         */
        get: operations["getCategories"];
        put?: never;
        /**
         * Create a new category
         * @description Create a new Dutch culture category
         */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a category by ID
         * @description Retrieve a specific category by its ID
         */
        get: operations["getCategoryById"];
        put?: never;
        post?: never;
        /**
         * Delete a category
         * @description Delete a specific category by its ID
         */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        /**
         * Update a category
         * @description Update a specific category by its ID
         */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/things": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all things
         * @description Retrieve a list of all Dutch cultural items
         */
        get: operations["getThings"];
        put?: never;
        /**
         * Create a new thing
         * @description Create a new Dutch cultural item
         */
        post: operations["createThing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/things/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a thing by ID
         * @description Retrieve a specific cultural item by its ID
         */
        get: operations["getThingById"];
        put?: never;
        post?: never;
        /**
         * Delete a thing
         * @description Delete a specific cultural item by its ID
         */
        delete: operations["deleteThing"];
        options?: never;
        head?: never;
        /**
         * Update a thing
         * @description Update a specific cultural item by its ID
         */
        patch: operations["updateThing"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Category: {
            /** @description Unique identifier for the category */
            id: number;
            /** @description Name of the category */
            name: string;
            /** @description Detailed description of the category */
            description: string;
        };
        CategoryInput: {
            /** @description Name of the category */
            name: string;
            /** @description Detailed description of the category */
            description: string;
        };
        Thing: {
            /** @description Unique identifier for the thing */
            id: number;
            /** @description Name of the cultural item */
            name: string;
            /** @description Description of the cultural item */
            description: string;
            /** @description Category the item belongs to */
            category: string;
            /**
             * Format: uri
             * @description Optional Wikipedia URL for the item (or null)
             */
            wikipedia?: string | null;
        };
        ThingInput: {
            /** @description Name of the cultural item */
            name: string;
            /** @description Description of the cultural item */
            description: string;
            /** @description Category the item belongs to */
            category: string;
            /**
             * Format: uri
             * @description Optional Wikipedia URL for the item (or null)
             */
            wikipedia?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCategories: {
        parameters: {
            query?: {
                /** @description Filter by category ID */
                id?: number;
                /** @description Filter by category name */
                name?: string;
                /** @description Filter by description */
                description?: string;
                /** @description Full-text search across all fields */
                q?: string;
                /** @description Page number for pagination (default: 1) */
                _page?: number;
                /** @description Number of items per page (default: 10) */
                _limit?: number;
                /** @description Field to sort by */
                _sort?: "id" | "name" | "description";
                /** @description Sort order: 'asc' for ascending or 'desc' for descending (default: asc) */
                _order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        responses: {
            /** @description Category created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    getCategoryById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        responses: {
            /** @description Category updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getThings: {
        parameters: {
            query?: {
                /** @description Filter by thing ID */
                id?: number;
                /** @description Filter by name */
                name?: string;
                /** @description Filter by description */
                description?: string;
                /** @description Filter by category */
                category?: string;
                /** @description Filter by Wikipedia URL */
                wikipedia?: string;
                /** @description Full-text search across all fields */
                q?: string;
                /** @description Page number for pagination (default: 1) */
                _page?: number;
                /** @description Number of items per page (default: 10) */
                _limit?: number;
                /** @description Field to sort by */
                _sort?: "id" | "name" | "description" | "category" | "wikipedia";
                /** @description Sort order: 'asc' for ascending or 'desc' for descending (default: asc) */
                _order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thing"][];
                };
            };
        };
    };
    createThing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThingInput"];
            };
        };
        responses: {
            /** @description Thing created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thing"];
                };
            };
        };
    };
    getThingById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Thing ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thing found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thing"];
                };
            };
            /** @description Thing not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteThing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Thing ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thing deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Thing not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateThing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Thing ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThingInput"];
            };
        };
        responses: {
            /** @description Thing updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thing"];
                };
            };
            /** @description Thing not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
